[package]
name = "prayer_times"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"

[dev-dependencies]
nanoserde = "0.1.32"
proptest = "1.0.0"
proptest-derive = "0.3.0"
