[package]
name = "prayer_times"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
nanoserde = "0.1.32"
proptest = "1.0.0"
